services:
  - type: web
    name: zyro-stream
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --production
    startCommand: node server.js
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
